name: JVM Image Push

on: [push, pull_request]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'refs/tags/v')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@2

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CI_PERSONAL_ACCESS_TOKEN }}

      - name: Build and push Docker image(JRE)
        id: build-and-push
        uses: docker/build-push-action@4
        with:
          platforms: linux/amd64,linux/arm64
          context: jvm/
          file: jvm/jre.Dockerfile
          push: true
          tags: base-image-jre-${GITHUB_REF#refs/tags/v}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Docker image(JDK)
        id: build-and-push
        uses: docker/build-push-action@4
        with:
          platforms: linux/amd64,linux/arm64
          context: jvm/
          file: jvm/jdk.Dockerfile
          push: true
          tags: base-image-jdk:${GITHUB_REF#refs/tags/v}
          cache-from: type=gha
          cache-to: type=gha,mode=max
