name: JVM Image Push

on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    strategy:
      matrix:
        image: [jre, jdk]
    runs-on: ubuntu-latest
    permissions:
      packages: write
    if: startsWith(github.event.ref, 'refs/tags/v')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2.4.1

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Metadata action(${{ matrix.image }})
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.image }}
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push Docker image(${{ matrix.image }})
        uses: docker/build-push-action@v4.0.0
        with:
          platforms: linux/amd64,linux/arm64
          context: jvm/
          file: jvm/${{ matrix.image }}.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}

